### PR TITLE
fix: support androidx

### PR DESCRIPTION
**Pull request by nawbc**
support androidx

### CODE REVIEW

**Comment by Akash9151** [comment]
Have you added the androidx support?

**Comment by han9088** [comment]
@Akash9151 yes

**Comment by ghost** [comment]
@sewerganger I forked your repository and was going to add setPlaybackSpeed method and then create a pull request to your repository but I failed. Can you add that function too?

**Comment by sewerganger** [comment]
original author seems to abandoned this repository , l can't pull request too

**Comment by sewerganger** [comment]
@nactrem10 original author seems to abandoned this repository . l can't pull request too, i am not a contributor

**Comment by han9088** [comment]
@nactrem10 original author seems to abandon this repository , l can't pull request too, i am not a contributor

**Comment by ghost** [comment]
@sewerganger Thank you for your attention.

**Pull request closed without merging**
